services:

  btop:

    image: bigbeartechworld/big-bear-btop:latest
    container_name: btop
    ports:
      - "7681:7681"
    restart: unless-stopped
    privileged: true
    volumes:
      - /proc:/proc
      - /sys:/sys
      - /dev:/dev
#      - /etc/localtime:/etc/localtime:ro
